/** MySQL: 集約とウィンドウ関数 */
import type { SqlFuncGroup } from "../types";

export const MYSQL_AGGREGATE: SqlFuncGroup[] = [
  {
    category: "集約",
    items: [
      {
        name: "COUNT",
        signature: "COUNT(*) / COUNT(列) / COUNT(DISTINCT 列)",
        summary: "行数を数える",
        example: "SELECT COUNT(*), COUNT(v), COUNT(DISTINCT v) FROM (SELECT 1 v UNION ALL SELECT 1 UNION ALL SELECT NULL) t",
        result: "3 | 2 | 1",
        note: "COUNT(*) は行を数え、COUNT(列) は NULL でない行だけを数える。ここを取り違えると件数が合わなくなる",
        keywords: ["件数", "カウント", "重複除外"],
      },
      {
        name: "SUM",
        signature: "SUM([DISTINCT] 数値)",
        summary: "合計を返す",
        example: "SELECT SUM(v) FROM (SELECT 1 v UNION ALL SELECT 2 UNION ALL SELECT NULL) t",
        result: "3",
        note: "1行も無いときは 0 ではなく NULL。0にしたいときは COALESCE(SUM(v), 0)",
        keywords: ["合計", "総和"],
      },
      {
        name: "AVG",
        signature: "AVG([DISTINCT] 数値)",
        summary: "平均を返す",
        example: "SELECT AVG(v) FROM (SELECT 1 v UNION ALL SELECT 2 UNION ALL SELECT NULL) t",
        result: "1.5000",
        note: "NULL は数に入らない (NULLを0として平均したいなら AVG(COALESCE(v,0)))",
        keywords: ["平均"],
      },
      {
        name: "MAX",
        signature: "MAX(値)",
        summary: "一番大きい値を返す",
        example: "SELECT MAX(v) FROM (SELECT 1 v UNION ALL SELECT 5) t",
        result: "5",
        note: "文字列や日付にも使える。1行の中で比べたいときは GREATEST",
        keywords: ["最大"],
      },
      {
        name: "MIN",
        signature: "MIN(値)",
        summary: "一番小さい値を返す",
        example: "SELECT MIN(v) FROM (SELECT 1 v UNION ALL SELECT 5) t",
        result: "1",
        keywords: ["最小"],
      },
      {
        name: "GROUP_CONCAT",
        signature: "GROUP_CONCAT([DISTINCT] 列 [ORDER BY ...] [SEPARATOR 区切り])",
        summary: "グループの値を1つの文字列にまとめる",
        example: "SELECT GROUP_CONCAT(v ORDER BY v SEPARATOR '/') FROM (SELECT 'b' v UNION ALL SELECT 'a') t",
        result: "a/b",
        note: "既定の上限が1024バイトで、超えると黙って切られる。長くなるなら group_concat_max_len を上げる。PostgreSQLの STRING_AGG にあたる",
        keywords: ["連結", "まとめる", "STRING_AGG"],
      },
      {
        name: "COUNT(DISTINCT)",
        signature: "COUNT(DISTINCT 列1 [, 列2 ...])",
        summary: "重複を除いた件数を数える",
        example: "SELECT COUNT(DISTINCT v) FROM (SELECT 1 v UNION ALL SELECT 1 UNION ALL SELECT 2) t",
        result: "2",
        note: "複数の列を渡すと、その組み合わせの種類数になる",
        keywords: ["重複", "種類数", "ユニーク"],
      },
      {
        name: "SUM(CASE)",
        signature: "SUM(CASE WHEN 条件 THEN 1 ELSE 0 END)",
        summary: "条件に当てはまる行だけを数える (横に並べた集計)",
        example: "SELECT SUM(CASE WHEN v > 1 THEN 1 ELSE 0 END) FROM (SELECT 1 v UNION ALL SELECT 2 UNION ALL SELECT 3) t",
        result: "2",
        note: "月ごとの列を横に並べる、いわゆる横持ち集計の定番。COUNT(CASE WHEN 条件 THEN 1 END) でも同じことができる",
        keywords: ["条件付き集計", "横持ち", "クロス集計", "ピボット"],
      },
    ],
  },
  {
    category: "ウィンドウ",
    items: [
      {
        name: "ROW_NUMBER",
        signature: "ROW_NUMBER() OVER (PARTITION BY 列 ORDER BY 列)",
        summary: "並べた順に1から番号を振る",
        example: "SELECT v, ROW_NUMBER() OVER (ORDER BY v) FROM (SELECT 10 v UNION ALL SELECT 10 UNION ALL SELECT 20) t",
        result: "10 | 1\n10 | 2\n20 | 3",
        since: "MySQL 8.0",
        note: "同じ値でも別の番号が付く。「グループごとの最新1件」を取るのに、番号1で絞る形がよく使われる",
        keywords: ["連番", "順位", "採番", "最新1件"],
      },
      {
        name: "RANK",
        signature: "RANK() OVER (ORDER BY 列)",
        summary: "同じ値には同じ順位を付ける (次は飛ぶ)",
        example: "SELECT v, RANK() OVER (ORDER BY v) FROM (SELECT 10 v UNION ALL SELECT 10 UNION ALL SELECT 20) t",
        result: "10 | 1\n10 | 1\n20 | 3",
        since: "MySQL 8.0",
        note: "1,1,3 と飛ぶ。飛ばしたくなければ DENSE_RANK",
        keywords: ["順位", "ランキング"],
      },
      {
        name: "DENSE_RANK",
        signature: "DENSE_RANK() OVER (ORDER BY 列)",
        summary: "同じ値には同じ順位を付ける (次は飛ばさない)",
        example: "SELECT v, DENSE_RANK() OVER (ORDER BY v) FROM (SELECT 10 v UNION ALL SELECT 10 UNION ALL SELECT 20) t",
        result: "10 | 1\n10 | 1\n20 | 2",
        since: "MySQL 8.0",
        keywords: ["順位", "ランキング"],
      },
      {
        name: "LAG",
        signature: "LAG(列 [, 何行前, 無いときの値]) OVER (ORDER BY 列)",
        summary: "前の行の値を持ってくる",
        example: "SELECT v, LAG(v) OVER (ORDER BY v) FROM (SELECT 10 v UNION ALL SELECT 20) t",
        result: "10 | NULL\n20 | 10",
        since: "MySQL 8.0",
        note: "前月比・前日差を出すのに使う (`v - LAG(v) OVER (ORDER BY 月)`)。前の行が無いところは NULL になるので、第3引数で既定値を渡せる (LAG(v, 1, 0))",
        keywords: ["前の行", "前月比", "差分"],
      },
      {
        name: "LEAD",
        signature: "LEAD(列 [, 何行後, 無いときの値]) OVER (ORDER BY 列)",
        summary: "次の行の値を持ってくる",
        example: "SELECT v, LEAD(v) OVER (ORDER BY v) FROM (SELECT 10 v UNION ALL SELECT 20) t",
        result: "10 | 20\n20 | NULL",
        since: "MySQL 8.0",
        note: "次の行が無いところは NULL。第3引数で既定値を渡せる (LEAD(v, 1, 0))",
        keywords: ["次の行"],
      },
      {
        name: "SUM() OVER",
        signature: "SUM(列) OVER (PARTITION BY 列 ORDER BY 列)",
        summary: "累計を出す (行をまとめずに集計する)",
        example: "SELECT v, SUM(v) OVER (ORDER BY v) FROM (SELECT 10 v UNION ALL SELECT 20 UNION ALL SELECT 30) t",
        result: "10 | 10\n20 | 30\n30 | 60",
        since: "MySQL 8.0",
        note: "ORDER BY を付けると累計、付けないとグループ全体の合計になる",
        keywords: ["累計", "running total", "移動合計"],
      },
      {
        name: "FIRST_VALUE",
        signature: "FIRST_VALUE(列) OVER (PARTITION BY 列 ORDER BY 列)",
        summary: "並びの先頭の値を持ってくる",
        example: "SELECT v, FIRST_VALUE(v) OVER (ORDER BY v) FROM (SELECT 20 v UNION ALL SELECT 10) t",
        result: "10 | 10\n20 | 10",
        since: "MySQL 8.0",
        note: "末尾は LAST_VALUE だが、既定の範囲では「今の行まで」なので、期待どおりにするには ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING を付ける",
        keywords: ["先頭", "最初の値"],
      },
      {
        name: "NTILE",
        signature: "NTILE(分割数) OVER (ORDER BY 列)",
        summary: "並べた行を指定の数の組に分ける",
        example: "SELECT v, NTILE(2) OVER (ORDER BY v) FROM (SELECT 10 v UNION ALL SELECT 20 UNION ALL SELECT 30 UNION ALL SELECT 40) t",
        result: "10 | 1\n20 | 1\n30 | 2\n40 | 2",
        since: "MySQL 8.0",
        keywords: ["四分位", "分割", "グループ分け"],
      },
    ],
  },
];
