/** MySQL: 日付・時刻の関数 */
import type { SqlFuncGroup } from "../types";

export const MYSQL_DATETIME: SqlFuncGroup[] = [
  {
    category: "日付・時刻",
    items: [
      {
        name: "NOW",
        signature: "NOW()",
        summary: "今の日時を返す",
        example: "SELECT NOW()",
        result: "2026-09-04 12:34:56 (実行した時刻による)",
        note: "1つの文の中では同じ値を返す。文ごとに取り直したいときは SYSDATE() を使う",
        keywords: ["現在", "今", "CURRENT_TIMESTAMP"],
      },
      {
        name: "CURDATE",
        signature: "CURDATE()",
        summary: "今日の日付を返す (時刻なし)",
        example: "SELECT CURDATE()",
        result: "2026-09-04 (実行した日による)",
        note: "CURRENT_DATE も同じ。「今日のぶん」を絞るときは `at >= CURDATE() AND at < CURDATE() + INTERVAL 1 DAY` と書くと索引が効く",
        keywords: ["今日", "CURRENT_DATE"],
      },
      {
        name: "CURTIME",
        signature: "CURTIME()",
        summary: "今の時刻を返す (日付なし)",
        example: "SELECT CURTIME()",
        result: "12:34:56 (実行した時刻による)",
        keywords: ["現在時刻", "CURRENT_TIME"],
      },
      {
        name: "DATE_FORMAT",
        signature: "DATE_FORMAT(日時, 書式)",
        summary: "日時を指定の書式の文字列にする",
        example: "SELECT DATE_FORMAT('2026-09-04 15:06:07', '%Y/%m/%d %H:%i:%s')",
        result: "2026/09/04 15:06:07",
        note: "%Y=4桁の年 %y=2桁 %m=月 %d=日 %H=24時間 %h=12時間 %i=分 %s=秒 %W=曜日名 %j=通算日。分は %m ではなく %i (ここを間違えやすい)",
        keywords: ["書式", "フォーマット", "整形", "文字列化"],
      },
      {
        name: "STR_TO_DATE",
        signature: "STR_TO_DATE(文字列, 書式)",
        summary: "文字列を書式に沿って日時に直す",
        example: "SELECT STR_TO_DATE('2026年09月04日', '%Y年%m月%d日')",
        result: "2026-09-04",
        note: "DATE_FORMAT の逆。書式が合わないと NULL になる",
        keywords: ["変換", "パース", "文字列から日付"],
      },
      {
        name: "DATE_ADD",
        signature: "DATE_ADD(日時, INTERVAL 数 単位)",
        summary: "日時に足す",
        example: "SELECT DATE_ADD('2026-01-31', INTERVAL 1 MONTH)",
        result: "2026-02-28",
        note: "単位は SECOND / MINUTE / HOUR / DAY / WEEK / MONTH / QUARTER / YEAR。月末に月を足すと、その月の月末に丸められる。`日時 + INTERVAL 1 MONTH` と書いても同じ",
        keywords: ["加算", "足す", "INTERVAL", "翌月"],
      },
      {
        name: "DATE_SUB",
        signature: "DATE_SUB(日時, INTERVAL 数 単位)",
        summary: "日時から引く",
        example: "SELECT DATE_SUB('2026-09-04', INTERVAL 7 DAY)",
        result: "2026-08-28",
        keywords: ["減算", "引く", "前日", "先月"],
      },
      {
        name: "DATEDIFF",
        signature: "DATEDIFF(日時1, 日時2)",
        summary: "日数の差を返す (日時1 - 日時2)",
        example: "SELECT DATEDIFF('2026-09-04', '2026-08-28')",
        result: "7",
        note: "時刻は切り捨てて日付だけで数える。引数の順が「新しい方が先」なのを間違えやすい",
        keywords: ["差", "日数", "経過"],
      },
      {
        name: "TIMESTAMPDIFF",
        signature: "TIMESTAMPDIFF(単位, 日時1, 日時2)",
        summary: "指定の単位で差を返す (日時2 - 日時1)",
        example: "SELECT TIMESTAMPDIFF(YEAR, '1990-09-05', '2026-09-04')",
        result: "35",
        note: "DATEDIFF とは引数の順が逆 (こちらは後ろから前を引く)。年齢の計算はこれが正確",
        keywords: ["差", "年齢", "経過", "月数"],
      },
      {
        name: "TIMESTAMPADD",
        signature: "TIMESTAMPADD(単位, 数, 日時)",
        summary: "単位を指定して日時に足す",
        example: "SELECT TIMESTAMPADD(HOUR, 3, '2026-09-04 10:00:00')",
        result: "2026-09-04 13:00:00",
        keywords: ["加算"],
      },
      {
        name: "YEAR",
        signature: "YEAR(日時)",
        summary: "年を取り出す",
        example: "SELECT YEAR('2026-09-04')",
        result: "2026",
        keywords: ["年"],
      },
      {
        name: "MONTH",
        signature: "MONTH(日時)",
        summary: "月を取り出す (1〜12)",
        example: "SELECT MONTH('2026-09-04')",
        result: "9",
        note: "2桁で欲しいときは DATE_FORMAT(日時, '%m')",
        keywords: ["月"],
      },
      {
        name: "DAY",
        signature: "DAY(日時)",
        summary: "日を取り出す (1〜31)",
        example: "SELECT DAY('2026-09-04')",
        result: "4",
        note: "DAYOFMONTH も同じ",
        keywords: ["日"],
      },
      {
        name: "HOUR",
        signature: "HOUR(日時)",
        summary: "時を取り出す",
        example: "SELECT HOUR('2026-09-04 15:06:07')",
        result: "15",
        keywords: ["時"],
      },
      {
        name: "MINUTE",
        signature: "MINUTE(日時)",
        summary: "分を取り出す",
        example: "SELECT MINUTE('2026-09-04 15:06:07')",
        result: "6",
        keywords: ["分"],
      },
      {
        name: "SECOND",
        signature: "SECOND(日時)",
        summary: "秒を取り出す",
        example: "SELECT SECOND('2026-09-04 15:06:07')",
        result: "7",
        keywords: ["秒"],
      },
      {
        name: "DATE",
        signature: "DATE(日時)",
        summary: "日付の部分だけを取り出す",
        example: "SELECT DATE('2026-09-04 15:06:07')",
        result: "2026-09-04",
        note: "WHERE DATE(at) = '2026-09-04' と書くと索引が効かない。範囲で書くほうが速い",
        keywords: ["日付", "時刻を落とす"],
      },
      {
        name: "TIME",
        signature: "TIME(日時)",
        summary: "時刻の部分だけを取り出す",
        example: "SELECT TIME('2026-09-04 15:06:07')",
        result: "15:06:07",
        keywords: ["時刻"],
      },
      {
        name: "LAST_DAY",
        signature: "LAST_DAY(日時)",
        summary: "その月の末日を返す",
        example: "SELECT LAST_DAY('2026-02-10')",
        result: "2026-02-28",
        note: "月初は DATE_SUB(日付, INTERVAL DAY(日付)-1 DAY) か DATE_FORMAT(日付,'%Y-%m-01')",
        keywords: ["月末", "末日"],
      },
      {
        name: "DAYOFWEEK",
        signature: "DAYOFWEEK(日時)",
        summary: "曜日を数で返す (1=日曜 〜 7=土曜)",
        example: "SELECT DAYOFWEEK('2026-09-04')",
        result: "6",
        note: "0=月曜で始まる WEEKDAY() もある。数え方が違うので取り違えやすい",
        keywords: ["曜日"],
      },
      {
        name: "WEEKDAY",
        signature: "WEEKDAY(日時)",
        summary: "曜日を数で返す (0=月曜 〜 6=日曜)",
        example: "SELECT WEEKDAY('2026-09-04')",
        result: "4",
        keywords: ["曜日"],
      },
      {
        name: "DAYNAME",
        signature: "DAYNAME(日時)",
        summary: "曜日名を返す",
        example: "SELECT DAYNAME('2026-09-04')",
        result: "Friday",
        note: "接続の言語設定 (lc_time_names) によって言語が変わる",
        keywords: ["曜日"],
      },
      {
        name: "DAYOFYEAR",
        signature: "DAYOFYEAR(日時)",
        summary: "1月1日から数えた通算日を返す",
        example: "SELECT DAYOFYEAR('2026-09-04')",
        result: "247",
        keywords: ["通算日"],
      },
      {
        name: "QUARTER",
        signature: "QUARTER(日時)",
        summary: "四半期を返す (1〜4)",
        example: "SELECT QUARTER('2026-09-04')",
        result: "3",
        keywords: ["四半期"],
      },
      {
        name: "WEEK",
        signature: "WEEK(日時 [, モード])",
        summary: "その年の何週目かを返す",
        example: "SELECT WEEK('2026-09-04', 1)",
        result: "36",
        note: "モードで週の始まりと数え方が変わる (0が既定、1は月曜始まり)。ISOの週番号は WEEKOFYEAR()",
        keywords: ["週", "週番号"],
      },
      {
        name: "UNIX_TIMESTAMP",
        signature: "UNIX_TIMESTAMP([日時])",
        summary: "1970-01-01からの秒数を返す",
        example: "SELECT UNIX_TIMESTAMP('2026-09-04 00:00:00')",
        result: "1788480000 (接続のタイムゾーンによる)",
        note: "引数なしだと今の時刻。値は接続のタイムゾーンで解釈される",
        keywords: ["エポック", "unixtime", "秒数"],
      },
      {
        name: "FROM_UNIXTIME",
        signature: "FROM_UNIXTIME(秒数 [, 書式])",
        summary: "秒数を日時に直す",
        example: "SELECT FROM_UNIXTIME(1788480000)",
        result: "2026-09-04 00:00:00 (接続のタイムゾーンによる)",
        note: "ミリ秒で入っている列は 1000 で割ってから渡す",
        keywords: ["エポック", "unixtime"],
      },
      {
        name: "CONVERT_TZ",
        signature: "CONVERT_TZ(日時, 元のタイムゾーン, 先のタイムゾーン)",
        summary: "タイムゾーンを変える",
        example: "SELECT CONVERT_TZ('2026-09-04 00:00:00', '+00:00', '+09:00')",
        result: "2026-09-04 09:00:00",
        note: "'Asia/Tokyo' のような名前を使うには、サーバーにタイムゾーンの表が入っている必要がある。'+09:00' の形なら常に使える",
        keywords: ["タイムゾーン", "時差", "JST", "UTC"],
      },
      {
        name: "MAKEDATE",
        signature: "MAKEDATE(年, 通算日)",
        summary: "年と通算日から日付を作る",
        example: "SELECT MAKEDATE(2026, 247)",
        result: "2026-09-04",
        keywords: ["日付を作る"],
      },
      {
        name: "SEC_TO_TIME",
        signature: "SEC_TO_TIME(秒数)",
        summary: "秒数を時:分:秒の形にする",
        example: "SELECT SEC_TO_TIME(3725)",
        result: "01:02:05",
        keywords: ["秒", "時間", "経過時間"],
      },
      {
        name: "TIME_TO_SEC",
        signature: "TIME_TO_SEC(時刻)",
        summary: "時:分:秒を秒数にする",
        example: "SELECT TIME_TO_SEC('01:02:05')",
        result: "3725",
        keywords: ["秒", "変換"],
      },
      {
        name: "TIMEDIFF",
        signature: "TIMEDIFF(日時1, 日時2)",
        summary: "時刻の差を時:分:秒で返す",
        example: "SELECT TIMEDIFF('2026-09-04 12:00:00', '2026-09-04 09:30:00')",
        result: "02:30:00",
        keywords: ["差", "経過時間"],
      },
    ],
  },
];
