/** MySQL: 条件・NULL・JSON・その他 */
import type { SqlFuncGroup } from "../types";

export const MYSQL_MISC: SqlFuncGroup[] = [
  {
    category: "条件・NULL",
    items: [
      {
        name: "CASE",
        signature: "CASE WHEN 条件 THEN 値 [WHEN ...] [ELSE 値] END",
        summary: "条件で値を振り分ける",
        example: "SELECT CASE WHEN 5 > 3 THEN '大' ELSE '小' END",
        result: "大",
        note: "`CASE 式 WHEN 値 THEN ...` の形もある (値が決まっているときはこちらが短い)。ELSE を書かないと、どれにも当てはまらない行は NULL になる",
        keywords: ["条件", "分岐", "IF", "振り分け"],
      },
      {
        name: "IF",
        signature: "IF(条件, 真のときの値, 偽のときの値)",
        summary: "条件で2つに振り分ける",
        example: "SELECT IF(5 > 3, '大', '小')",
        result: "大",
        note: "MySQL独自。PostgreSQLには無いので、移す予定があるなら CASE を使う",
        keywords: ["条件", "分岐"],
      },
      {
        name: "IFNULL",
        signature: "IFNULL(値, NULLのときの値)",
        summary: "NULLなら別の値に置き換える",
        example: "SELECT IFNULL(NULL, 0)",
        result: "0",
        note: "引数は2つまで。3つ以上を順に見たいときは COALESCE",
        keywords: ["NULL", "既定値", "置き換え"],
      },
      {
        name: "COALESCE",
        signature: "COALESCE(値1, 値2, ...)",
        summary: "最初にNULLでなかった値を返す",
        example: "SELECT COALESCE(NULL, NULL, 'A', 'B')",
        result: "A",
        note: "標準SQLなのでどのDBでも使える。すべてNULLなら結果もNULL",
        keywords: ["NULL", "既定値", "最初の値"],
      },
      {
        name: "NULLIF",
        signature: "NULLIF(値1, 値2)",
        summary: "2つが同じならNULL、違えば値1を返す",
        example: "SELECT NULLIF('', '')",
        result: "NULL",
        note: "0除算を避けるのに使う (`v / NULLIF(w, 0)` なら w=0 のときエラーではなくNULL)。空文字をNULL扱いにするのにも使える",
        keywords: ["NULL", "0除算", "空文字"],
      },
      {
        name: "IS NULL",
        signature: "値 IS NULL / 値 IS NOT NULL",
        summary: "NULLかどうかを調べる",
        example: "SELECT NULL IS NULL, NULL = NULL",
        result: "1 | NULL",
        note: "`= NULL` では判定できない (結果がNULLになり、条件としては偽になる)。ここが一番よく引っかかる所",
        keywords: ["NULL", "判定"],
      },
      {
        name: "<=>",
        signature: "値1 <=> 値2",
        summary: "NULL同士も等しいとみなして比べる",
        example: "SELECT NULL <=> NULL, 1 <=> NULL",
        result: "1 | 0",
        note: "MySQL独自。NULLを含む列の突き合わせに使える",
        keywords: ["NULL", "比較", "等価"],
      },
    ],
  },
  {
    category: "JSON",
    items: [
      {
        name: "JSON_EXTRACT",
        signature: "JSON_EXTRACT(JSON, パス)",
        summary: "JSONから値を取り出す",
        example: "SELECT JSON_EXTRACT('{\"a\": {\"b\": 1}}', '$.a.b')",
        result: "1",
        note: "`JSON列 -> '$.a.b'` と書いても同じ。取り出した文字列は引用符が付くので、外したいときは JSON_UNQUOTE か `->>` を使う",
        keywords: ["JSON", "取り出し", "パス"],
      },
      {
        name: "JSON_UNQUOTE",
        signature: "JSON_UNQUOTE(JSONの文字列)",
        summary: "JSONの文字列から引用符を外す",
        example: "SELECT JSON_UNQUOTE(JSON_EXTRACT('{\"a\": \"x\"}', '$.a'))",
        result: "x",
        note: "`JSON列 ->> '$.a'` が同じ意味の短い書き方",
        keywords: ["JSON", "引用符"],
      },
      {
        name: "JSON_OBJECT",
        signature: "JSON_OBJECT(キー1, 値1, キー2, 値2, ...)",
        summary: "JSONのオブジェクトを作る",
        example: "SELECT JSON_OBJECT('id', 1, 'name', 'A')",
        result: '{"id": 1, "name": "A"}',
        keywords: ["JSON", "作る"],
      },
      {
        name: "JSON_ARRAY",
        signature: "JSON_ARRAY(値1, 値2, ...)",
        summary: "JSONの配列を作る",
        example: "SELECT JSON_ARRAY(1, 'a', NULL)",
        result: '[1, "a", null]',
        keywords: ["JSON", "配列"],
      },
      {
        name: "JSON_LENGTH",
        signature: "JSON_LENGTH(JSON [, パス])",
        summary: "要素の数を返す",
        example: "SELECT JSON_LENGTH('[1, 2, 3]')",
        result: "3",
        keywords: ["JSON", "件数"],
      },
      {
        name: "JSON_CONTAINS",
        signature: "JSON_CONTAINS(JSON, 探す値 [, パス])",
        summary: "その値を含むかを返す",
        example: "SELECT JSON_CONTAINS('[1, 2, 3]', '2')",
        result: "1",
        note: "探す値もJSONとして渡す (文字列を探すなら '\"a\"' のように引用符ごと)",
        keywords: ["JSON", "含む"],
      },
      {
        name: "JSON_SET",
        signature: "JSON_SET(JSON, パス, 値 [, パス, 値 ...])",
        summary: "値を入れ替える (無ければ足す)",
        example: "SELECT JSON_SET('{\"a\": 1}', '$.b', 2)",
        result: '{"a": 1, "b": 2}',
        note: "足すだけなら JSON_INSERT、入れ替えるだけなら JSON_REPLACE",
        keywords: ["JSON", "更新"],
      },
      {
        name: "JSON_REMOVE",
        signature: "JSON_REMOVE(JSON, パス)",
        summary: "指定した所を取り除く",
        example: "SELECT JSON_REMOVE('{\"a\": 1, \"b\": 2}', '$.b')",
        result: '{"a": 1}',
        keywords: ["JSON", "削除"],
      },
      {
        name: "JSON_KEYS",
        signature: "JSON_KEYS(JSON [, パス])",
        summary: "キーの一覧を配列で返す",
        example: "SELECT JSON_KEYS('{\"a\": 1, \"b\": 2}')",
        result: '["a", "b"]',
        keywords: ["JSON", "キー"],
      },
      {
        name: "JSON_VALID",
        signature: "JSON_VALID(文字列)",
        summary: "JSONとして正しいかを返す",
        example: "SELECT JSON_VALID('{\"a\": 1}'), JSON_VALID('{a: 1}')",
        result: "1 | 0",
        keywords: ["JSON", "検証"],
      },
    ],
  },
  {
    category: "その他",
    items: [
      {
        name: "DATABASE",
        signature: "DATABASE()",
        summary: "今つないでいるデータベース名を返す",
        example: "SELECT DATABASE()",
        result: "つないでいるDB名 (接続による)",
        keywords: ["DB名", "スキーマ"],
      },
      {
        name: "USER",
        signature: "USER()",
        summary: "今の接続ユーザーを返す",
        example: "SELECT USER()",
        result: "user@host (接続による)",
        note: "CURRENT_USER() は権限の判定に使われているほうのユーザーを返す (別物になることがある)",
        keywords: ["ユーザー"],
      },
      {
        name: "VERSION",
        signature: "VERSION()",
        summary: "サーバーの版を返す",
        example: "SELECT VERSION()",
        result: "8.0.x など (接続による)",
        keywords: ["バージョン", "版"],
      },
      {
        name: "LAST_INSERT_ID",
        signature: "LAST_INSERT_ID()",
        summary: "直前のINSERTで採番された自動連番を返す",
        example: "SELECT LAST_INSERT_ID()",
        result: "直前のINSERTによる",
        note: "接続ごとに別々に覚えているので、他の人のINSERTには影響されない",
        keywords: ["採番", "AUTO_INCREMENT", "連番"],
      },
      {
        name: "UUID",
        signature: "UUID()",
        summary: "重複しない36文字のIDを作る",
        example: "SELECT UUID()",
        result: "実行のたびに変わる",
        note: "主キーに使うと索引が飛び飛びになって遅くなりやすい。UUID_TO_BIN(uuid, 1) で16バイトに詰めて持つ手もある",
        keywords: ["UUID", "採番", "ID"],
      },
      {
        name: "ROW_COUNT",
        signature: "ROW_COUNT()",
        summary: "直前の更新で変わった行数を返す",
        example: "SELECT ROW_COUNT()",
        result: "直前の文による",
        keywords: ["件数", "更新"],
      },
    ],
  },
];
