/** MySQL: 数値と型変換の関数 */
import type { SqlFuncGroup } from "../types";

export const MYSQL_NUMBER: SqlFuncGroup[] = [
  {
    category: "数値",
    items: [
      {
        name: "ROUND",
        signature: "ROUND(数値 [, 小数桁数])",
        summary: "四捨五入する",
        example: "SELECT ROUND(1234.5678, 2)",
        result: "1234.57",
        note: "桁数に負の数を渡すと、10の位・100の位で丸められる (ROUND(1234, -2) → 1200)",
        keywords: ["四捨五入", "丸め"],
      },
      {
        name: "TRUNCATE",
        signature: "TRUNCATE(数値, 小数桁数)",
        summary: "切り捨てる (四捨五入しない)",
        example: "SELECT TRUNCATE(1234.5678, 2)",
        result: "1234.56",
        note: "桁数の指定が必須。0を渡すと整数部だけになる",
        keywords: ["切り捨て", "切捨"],
      },
      {
        name: "CEIL",
        signature: "CEIL(数値)",
        summary: "切り上げる (以上で一番小さい整数)",
        example: "SELECT CEIL(1.2)",
        result: "2",
        note: "CEILING も同じ。負の数では -1.2 → -1 になる",
        keywords: ["切り上げ", "CEILING"],
      },
      {
        name: "FLOOR",
        signature: "FLOOR(数値)",
        summary: "切り下げる (以下で一番大きい整数)",
        example: "SELECT FLOOR(-1.2)",
        result: "-2",
        note: "負の数では「0に近づく」のではなく小さいほうへ動くので、切り捨てのつもりで使うと合わないことがある",
        keywords: ["切り捨て", "床"],
      },
      {
        name: "ABS",
        signature: "ABS(数値)",
        summary: "絶対値を返す",
        example: "SELECT ABS(-12.5)",
        result: "12.5",
        keywords: ["絶対値"],
      },
      {
        name: "MOD",
        signature: "MOD(数値, 割る数)",
        summary: "割った余りを返す",
        example: "SELECT MOD(10, 3)",
        result: "1",
        note: "`10 % 3` と書いても同じ。0で割ると NULL になる (エラーにはならない)",
        keywords: ["余り", "剰余", "%"],
      },
      {
        name: "POWER",
        signature: "POWER(数値, 指数)",
        summary: "べき乗を返す",
        example: "SELECT POWER(2, 10)",
        result: "1024",
        note: "POW も同じ",
        keywords: ["べき乗", "累乗", "POW"],
      },
      {
        name: "SQRT",
        signature: "SQRT(数値)",
        summary: "平方根を返す",
        example: "SELECT SQRT(16)",
        result: "4",
        keywords: ["平方根", "ルート"],
      },
      {
        name: "SIGN",
        signature: "SIGN(数値)",
        summary: "符号を返す (正=1 / 0=0 / 負=-1)",
        example: "SELECT SIGN(-3)",
        result: "-1",
        keywords: ["符号"],
      },
      {
        name: "GREATEST",
        signature: "GREATEST(値1, 値2, ...)",
        summary: "並べた値のうち一番大きいものを返す",
        example: "SELECT GREATEST(3, 9, 5)",
        result: "9",
        note: "行をまたいだ最大は MAX()。こちらは1行の中で比べる。1つでもNULLがあると結果はNULL",
        keywords: ["最大", "大きい方"],
      },
      {
        name: "LEAST",
        signature: "LEAST(値1, 値2, ...)",
        summary: "並べた値のうち一番小さいものを返す",
        example: "SELECT LEAST(3, 9, 5)",
        result: "3",
        keywords: ["最小", "小さい方"],
      },
      {
        name: "RAND",
        signature: "RAND([種])",
        summary: "0以上1未満の乱数を返す",
        example: "SELECT FLOOR(RAND() * 100)",
        result: "0〜99 のどれか (実行のたびに変わる)",
        note: "種を渡すと毎回同じ並びになる。ORDER BY RAND() は全行に乱数を振るので、大きな表では重い",
        keywords: ["乱数", "ランダム"],
      },
      {
        name: "LOG",
        signature: "LOG([底, ] 数値)",
        summary: "対数を返す (底を省くと自然対数)",
        example: "SELECT ROUND(LOG(10, 1000), 4)",
        result: "3.0000",
        keywords: ["対数"],
      },
      {
        name: "EXP",
        signature: "EXP(数値)",
        summary: "eのべき乗を返す",
        example: "SELECT ROUND(EXP(1), 4)",
        result: "2.7183",
        keywords: ["指数"],
      },
      {
        name: "PI",
        signature: "PI()",
        summary: "円周率を返す",
        example: "SELECT ROUND(PI(), 5)",
        result: "3.14159",
        keywords: ["円周率"],
      },
    ],
  },
  {
    category: "型変換",
    items: [
      {
        name: "CAST",
        signature: "CAST(値 AS 型)",
        summary: "型を変える",
        example: "SELECT CAST('0123' AS UNSIGNED)",
        result: "123",
        note: "型は CHAR / SIGNED / UNSIGNED / DECIMAL(桁,小数) / DATE / DATETIME / TIME / JSON など。文字列を数値にすると前ゼロは消える",
        keywords: ["変換", "キャスト", "型"],
      },
      {
        name: "CONVERT",
        signature: "CONVERT(値, 型) / CONVERT(文字列 USING 文字コード)",
        summary: "型または文字コードを変える",
        example: "SELECT CONVERT('12.7', DECIMAL(4,1))",
        result: "12.7",
        keywords: ["変換", "文字コード"],
      },
      {
        name: "BINARY",
        signature: "BINARY 値",
        summary: "バイト列として比べさせる (大文字小文字を区別する)",
        example: "SELECT BINARY 'abc' = 'ABC'",
        result: "0",
        note: "照合順序で大文字小文字を区別しない設定でも、これを付けると区別される",
        keywords: ["大文字小文字", "区別", "比較"],
      },
    ],
  },
];
