/** MySQL: 文字列と正規表現の関数 */
import type { SqlFuncGroup } from "../types";

export const MYSQL_TEXT: SqlFuncGroup[] = [
  {
    category: "文字列",
    items: [
      {
        name: "CONCAT",
        signature: "CONCAT(文字列1, 文字列2, ...)",
        summary: "文字列をつなげる",
        example: "SELECT CONCAT('A', '-', 'B')",
        result: "A-B",
        note: "1つでもNULLがあると、結果は全体がNULLになる。NULLを空文字として扱いたいときは CONCAT_WS か COALESCE を挟む",
        keywords: ["連結", "結合", "つなげる", "+"],
      },
      {
        name: "CONCAT_WS",
        signature: "CONCAT_WS(区切り文字, 文字列1, 文字列2, ...)",
        summary: "区切り文字を挟んでつなげる (NULLは飛ばす)",
        example: "SELECT CONCAT_WS('/', '2026', NULL, '04')",
        result: "2026/04",
        note: "WS は With Separator の略。NULLを飛ばすので、住所の結合などに向く",
        keywords: ["連結", "区切り", "NULL"],
      },
      {
        name: "SUBSTRING",
        signature: "SUBSTRING(文字列, 開始位置 [, 長さ])",
        summary: "文字列の一部を取り出す",
        example: "SELECT SUBSTRING('ABCDE', 2, 3)",
        result: "BCD",
        note: "開始位置は1始まり (0ではない)。負の数を渡すと末尾からの位置になる (-2 なら後ろから2文字目)。SUBSTR も同じ",
        keywords: ["部分", "切り出し", "SUBSTR", "MID"],
      },
      {
        name: "LEFT",
        signature: "LEFT(文字列, 文字数)",
        summary: "左から指定の文字数を取り出す",
        example: "SELECT LEFT('2026-09-04', 7)",
        result: "2026-09",
        keywords: ["先頭", "前方"],
      },
      {
        name: "RIGHT",
        signature: "RIGHT(文字列, 文字数)",
        summary: "右から指定の文字数を取り出す",
        example: "SELECT RIGHT('ORD-000123', 6)",
        result: "000123",
        keywords: ["末尾", "後方"],
      },
      {
        name: "LENGTH",
        signature: "LENGTH(文字列)",
        summary: "バイト数を返す",
        example: "SELECT LENGTH('あいう')",
        result: "9",
        note: "UTF-8の日本語は1文字3バイトなので、文字数が欲しいときは CHAR_LENGTH を使う",
        keywords: ["長さ", "バイト"],
      },
      {
        name: "CHAR_LENGTH",
        signature: "CHAR_LENGTH(文字列)",
        summary: "文字数を返す",
        example: "SELECT CHAR_LENGTH('あいう')",
        result: "3",
        note: "CHARACTER_LENGTH も同じ",
        keywords: ["長さ", "文字数"],
      },
      {
        name: "UPPER",
        signature: "UPPER(文字列)",
        summary: "大文字にする",
        example: "SELECT UPPER('abc')",
        result: "ABC",
        note: "UCASE も同じ",
        keywords: ["大文字", "UCASE"],
      },
      {
        name: "LOWER",
        signature: "LOWER(文字列)",
        summary: "小文字にする",
        example: "SELECT LOWER('ABC')",
        result: "abc",
        note: "LCASE も同じ",
        keywords: ["小文字", "LCASE"],
      },
      {
        name: "TRIM",
        signature: "TRIM([{BOTH|LEADING|TRAILING} 削る文字 FROM] 文字列)",
        summary: "前後の空白 (または指定の文字) を削る",
        example: "SELECT TRIM(LEADING '0' FROM '000123')",
        result: "123",
        note: "何も指定しなければ前後の空白を削る。片側だけなら LTRIM / RTRIM でも良い",
        keywords: ["空白", "削る", "前ゼロ"],
      },
      {
        name: "LTRIM",
        signature: "LTRIM(文字列)",
        summary: "左側の空白を削る",
        example: "SELECT CONCAT('[', LTRIM('  ab  '), ']')",
        result: "[ab  ]",
        keywords: ["空白"],
      },
      {
        name: "RTRIM",
        signature: "RTRIM(文字列)",
        summary: "右側の空白を削る",
        example: "SELECT CONCAT('[', RTRIM('  ab  '), ']')",
        result: "[  ab]",
        keywords: ["空白"],
      },
      {
        name: "LPAD",
        signature: "LPAD(文字列, 全体の長さ, 埋める文字)",
        summary: "左を埋めて指定の長さにする",
        example: "SELECT LPAD('123', 8, '0')",
        result: "00000123",
        note: "元が長さを超えていると切り詰められる",
        keywords: ["前ゼロ", "ゼロ埋め", "桁揃え"],
      },
      {
        name: "RPAD",
        signature: "RPAD(文字列, 全体の長さ, 埋める文字)",
        summary: "右を埋めて指定の長さにする",
        example: "SELECT CONCAT('[', RPAD('ab', 5, '.'), ']')",
        result: "[ab...]",
        keywords: ["桁揃え", "固定長"],
      },
      {
        name: "REPLACE",
        signature: "REPLACE(文字列, 探す文字列, 置き換える文字列)",
        summary: "文字列を置き換える (すべて)",
        example: "SELECT REPLACE('2026/09/04', '/', '-')",
        result: "2026-09-04",
        note: "大文字と小文字は区別される (照合順序によらず、バイトで比べる)",
        keywords: ["置換", "置き換え"],
      },
      {
        name: "INSTR",
        signature: "INSTR(文字列, 探す文字列)",
        summary: "見つかった位置を返す (無ければ0)",
        example: "SELECT INSTR('abcdef', 'cd')",
        result: "3",
        note: "1始まり。引数の順が逆の LOCATE(探す文字列, 文字列) もある",
        keywords: ["検索", "位置", "含む", "LOCATE"],
      },
      {
        name: "LOCATE",
        signature: "LOCATE(探す文字列, 文字列 [, 開始位置])",
        summary: "見つかった位置を返す (開始位置を指定できる)",
        example: "SELECT LOCATE('a', 'banana', 4)",
        result: "4",
        keywords: ["検索", "位置", "POSITION"],
      },
      {
        name: "SUBSTRING_INDEX",
        signature: "SUBSTRING_INDEX(文字列, 区切り文字, 個数)",
        summary: "区切り文字で数えて、その手前 (負なら後ろ) を取り出す",
        example: "SELECT SUBSTRING_INDEX('a.b.c', '.', 2)",
        result: "a.b",
        note: "個数が負だと後ろから数える。-1 で「最後の区切りより後ろ」が取れる (拡張子の取り出しなどに使う)",
        keywords: ["分割", "区切り", "split"],
      },
      {
        name: "REPEAT",
        signature: "REPEAT(文字列, 回数)",
        summary: "文字列を繰り返す",
        example: "SELECT REPEAT('ab', 3)",
        result: "ababab",
        keywords: ["繰り返し"],
      },
      {
        name: "REVERSE",
        signature: "REVERSE(文字列)",
        summary: "文字を逆順にする",
        example: "SELECT REVERSE('abc')",
        result: "cba",
        keywords: ["逆順"],
      },
      {
        name: "SPACE",
        signature: "SPACE(個数)",
        summary: "指定した数の空白を作る",
        example: "SELECT CONCAT('[', SPACE(3), ']')",
        result: "[   ]",
        keywords: ["空白"],
      },
      {
        name: "ELT",
        signature: "ELT(番号, 値1, 値2, ...)",
        summary: "番号で選んだ値を返す",
        example: "SELECT ELT(2, '未', '済', '保留')",
        result: "済",
        note: "区分コードを名前に直すのに使える (1始まり。範囲外はNULL)",
        keywords: ["区分", "コード変換"],
      },
      {
        name: "FIELD",
        signature: "FIELD(値, 値1, 値2, ...)",
        summary: "値が何番目にあるかを返す (無ければ0)",
        example: "SELECT FIELD('c', 'a', 'b', 'c')",
        result: "3",
        note: "ORDER BY FIELD(status,'急','中','低') と書くと、決めた順に並べられる",
        keywords: ["並び順", "ORDER BY", "任意順"],
      },
      {
        name: "FIND_IN_SET",
        signature: "FIND_IN_SET(探す文字列, カンマ区切りの文字列)",
        summary: "カンマ区切りの中で何番目かを返す (無ければ0)",
        example: "SELECT FIND_IN_SET('b', 'a,b,c')",
        result: "2",
        keywords: ["カンマ", "含む", "SET"],
      },
      {
        name: "FORMAT",
        signature: "FORMAT(数値, 小数桁数)",
        summary: "3桁ごとにカンマを打った文字列にする",
        example: "SELECT FORMAT(1234567.891, 2)",
        result: "1,234,567.89",
        note: "結果は文字列になるので、そのあと計算には使えない",
        keywords: ["カンマ", "桁区切り", "3桁"],
      },
      {
        name: "HEX",
        signature: "HEX(数値または文字列)",
        summary: "16進数の文字列にする",
        example: "SELECT HEX(255)",
        result: "FF",
        keywords: ["16進", "hex"],
      },
      {
        name: "MD5",
        signature: "MD5(文字列)",
        summary: "MD5のハッシュ値 (32文字) を返す",
        example: "SELECT MD5('abc')",
        result: "900150983cd24fb0d6963f7d28e17f72",
        note: "重複の突き合わせ用。パスワードの保存には使わない",
        keywords: ["ハッシュ"],
      },
      {
        name: "SHA2",
        signature: "SHA2(文字列, ビット長)",
        summary: "SHA-2のハッシュ値を返す",
        example: "SELECT SHA2('abc', 256)",
        result: "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
        note: "ビット長は 224 / 256 / 384 / 512",
        keywords: ["ハッシュ", "SHA256"],
      },
    ],
  },
  {
    category: "正規表現",
    items: [
      {
        name: "REGEXP_LIKE",
        signature: "REGEXP_LIKE(文字列, パターン [, オプション])",
        summary: "正規表現に当てはまるかを返す",
        example: "SELECT REGEXP_LIKE('AB-123', '^[A-Z]{2}-[0-9]+$')",
        result: "1",
        since: "MySQL 8.0",
        note: "オプションに 'i' を渡すと大文字小文字を区別しない。`文字列 REGEXP パターン` と書けば古い版でも動く",
        keywords: ["正規表現", "RLIKE", "REGEXP"],
      },
      {
        name: "REGEXP_SUBSTR",
        signature: "REGEXP_SUBSTR(文字列, パターン [, 開始位置, 何個目, オプション])",
        summary: "正規表現に当てはまった部分を取り出す",
        example: "SELECT REGEXP_SUBSTR('注文 ORD-123 済', '[A-Z]+-[0-9]+')",
        result: "ORD-123",
        keywords: ["正規表現", "抽出"],
      },
      {
        name: "REGEXP_REPLACE",
        signature: "REGEXP_REPLACE(文字列, パターン, 置換文字列)",
        summary: "正規表現に当てはまった部分を置き換える",
        example: "SELECT REGEXP_REPLACE('a1b2c3', '[0-9]', '')",
        result: "abc",
        note: "置換文字列の中では $1 で1つ目の括弧を参照できる",
        keywords: ["正規表現", "置換"],
      },
      {
        name: "REGEXP_INSTR",
        signature: "REGEXP_INSTR(文字列, パターン)",
        summary: "正規表現に当てはまった位置を返す (無ければ0)",
        example: "SELECT REGEXP_INSTR('abc123', '[0-9]')",
        result: "4",
        keywords: ["正規表現", "位置"],
      },
    ],
  },
];
