/** PostgreSQL: 集約とウィンドウ関数 */
import type { SqlFuncGroup } from "../types";

export const PG_AGGREGATE: SqlFuncGroup[] = [
  {
    category: "集約",
    items: [
      {
        name: "COUNT",
        signature: "COUNT(*) / COUNT(列) / COUNT(DISTINCT 列)",
        summary: "行数を数える",
        example: "SELECT COUNT(*), COUNT(v), COUNT(DISTINCT v) FROM (VALUES (1),(1),(NULL)) t(v)",
        result: "3 | 2 | 1",
        note: "COUNT(*) は行を数え、COUNT(列) は NULL でない行だけを数える。結果は bigint なので、割り算するときは型に注意",
        keywords: ["件数", "カウント"],
      },
      {
        name: "SUM",
        signature: "SUM(数値)",
        summary: "合計を返す",
        example: "SELECT SUM(v) FROM (VALUES (1),(2),(NULL)) t(v)",
        result: "3",
        note: "1行も無いときは 0 ではなく NULL。COALESCE(SUM(v), 0) で0にできる",
        keywords: ["合計"],
      },
      {
        name: "AVG",
        signature: "AVG(数値)",
        summary: "平均を返す",
        example: "SELECT ROUND(AVG(v), 2) FROM (VALUES (1),(2),(NULL)) t(v)",
        result: "1.50",
        note: "NULL は数に入らない",
        keywords: ["平均"],
      },
      {
        name: "MAX",
        signature: "MAX(値)",
        summary: "一番大きい値を返す",
        example: "SELECT MAX(v) FROM (VALUES (1),(5)) t(v)",
        result: "5",
        keywords: ["最大"],
      },
      {
        name: "MIN",
        signature: "MIN(値)",
        summary: "一番小さい値を返す",
        example: "SELECT MIN(v) FROM (VALUES (1),(5)) t(v)",
        result: "1",
        keywords: ["最小"],
      },
      {
        name: "STRING_AGG",
        signature: "STRING_AGG(文字列, 区切り [ORDER BY ...])",
        summary: "グループの値を1つの文字列にまとめる",
        example: "SELECT STRING_AGG(v, '/' ORDER BY v) FROM (VALUES ('b'),('a')) t(v)",
        result: "a/b",
        note: "MySQLの GROUP_CONCAT にあたる。長さの上限は無い。数値の列は ::text を付けてから渡す",
        keywords: ["連結", "まとめる", "GROUP_CONCAT"],
      },
      {
        name: "ARRAY_AGG",
        signature: "ARRAY_AGG(値 [ORDER BY ...])",
        summary: "グループの値を配列にまとめる",
        example: "SELECT ARRAY_AGG(v ORDER BY v) FROM (VALUES (2),(1)) t(v)",
        result: "{1,2}",
        keywords: ["配列", "まとめる"],
      },
      {
        name: "JSON_AGG",
        signature: "JSON_AGG(値) / JSONB_AGG(値)",
        summary: "グループの値をJSONの配列にまとめる",
        example: "SELECT JSON_AGG(v) FROM (VALUES (1),(2)) t(v)",
        result: "[1, 2]",
        note: "行そのものをまとめたいときは JSON_AGG(ROW_TO_JSON(t))",
        keywords: ["JSON", "まとめる"],
      },
      {
        name: "FILTER",
        signature: "集約関数(...) FILTER (WHERE 条件)",
        summary: "条件に当てはまる行だけを集計する",
        example: "SELECT COUNT(*) FILTER (WHERE v > 1) FROM (VALUES (1),(2),(3)) t(v)",
        result: "2",
        note: "SUM(CASE WHEN ... THEN 1 ELSE 0 END) より読みやすい。PostgreSQL独自 (MySQLには無い)",
        keywords: ["条件付き集計", "横持ち", "クロス集計"],
      },
      {
        name: "PERCENTILE_CONT",
        signature: "PERCENTILE_CONT(割合) WITHIN GROUP (ORDER BY 列)",
        summary: "中央値などの分位点を返す",
        example: "SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY v) FROM (VALUES (1),(2),(10)) t(v)",
        result: "2",
        note: "0.5 で中央値。値を間で補間せず実際にある値が欲しいときは PERCENTILE_DISC",
        keywords: ["中央値", "分位", "パーセンタイル"],
      },
      {
        name: "BOOL_OR",
        signature: "BOOL_OR(条件) / BOOL_AND(条件)",
        summary: "グループの中に1つでもあるか / すべてそうか",
        example: "SELECT BOOL_OR(v > 2), BOOL_AND(v > 0) FROM (VALUES (1),(3)) t(v)",
        result: "t | t",
        keywords: ["存在", "すべて", "真偽"],
      },
    ],
  },
  {
    category: "ウィンドウ",
    items: [
      {
        name: "ROW_NUMBER",
        signature: "ROW_NUMBER() OVER (PARTITION BY 列 ORDER BY 列)",
        summary: "並べた順に1から番号を振る",
        example: "SELECT v, ROW_NUMBER() OVER (ORDER BY v) FROM (VALUES (10),(10),(20)) t(v)",
        result: "10 | 1\n10 | 2\n20 | 3",
        note: "「グループごとの最新1件」を取るのに、番号1で絞る形がよく使われる。DISTINCT ON でも同じことができる",
        keywords: ["連番", "採番", "最新1件"],
      },
      {
        name: "RANK",
        signature: "RANK() OVER (ORDER BY 列)",
        summary: "同じ値には同じ順位を付ける (次は飛ぶ)",
        example: "SELECT v, RANK() OVER (ORDER BY v) FROM (VALUES (10),(10),(20)) t(v)",
        result: "10 | 1\n10 | 1\n20 | 3",
        keywords: ["順位", "ランキング"],
      },
      {
        name: "DENSE_RANK",
        signature: "DENSE_RANK() OVER (ORDER BY 列)",
        summary: "同じ値には同じ順位を付ける (次は飛ばさない)",
        example: "SELECT v, DENSE_RANK() OVER (ORDER BY v) FROM (VALUES (10),(10),(20)) t(v)",
        result: "10 | 1\n10 | 1\n20 | 2",
        keywords: ["順位"],
      },
      {
        name: "LAG",
        signature: "LAG(列 [, 何行前, 無いときの値]) OVER (ORDER BY 列)",
        summary: "前の行の値を持ってくる",
        example: "SELECT v, LAG(v, 1, 0) OVER (ORDER BY v) FROM (VALUES (10),(20)) t(v)",
        result: "10 | 0\n20 | 10",
        note: "前月比・前日差を出すのに使う",
        keywords: ["前の行", "前月比", "差分"],
      },
      {
        name: "LEAD",
        signature: "LEAD(列 [, 何行後, 無いときの値]) OVER (ORDER BY 列)",
        summary: "次の行の値を持ってくる",
        example: "SELECT v, LEAD(v, 1, 0) OVER (ORDER BY v) FROM (VALUES (10),(20)) t(v)",
        result: "10 | 20\n20 | 0",
        keywords: ["次の行"],
      },
      {
        name: "SUM() OVER",
        signature: "SUM(列) OVER (PARTITION BY 列 ORDER BY 列)",
        summary: "累計を出す (行をまとめずに集計する)",
        example: "SELECT v, SUM(v) OVER (ORDER BY v) FROM (VALUES (10),(20),(30)) t(v)",
        result: "10 | 10\n20 | 30\n30 | 60",
        note: "ORDER BY を付けると累計、付けないとグループ全体の合計になる",
        keywords: ["累計", "running total"],
      },
      {
        name: "FIRST_VALUE",
        signature: "FIRST_VALUE(列) OVER (PARTITION BY 列 ORDER BY 列)",
        summary: "並びの先頭の値を持ってくる",
        example: "SELECT v, FIRST_VALUE(v) OVER (ORDER BY v) FROM (VALUES (20),(10)) t(v)",
        result: "10 | 10\n20 | 10",
        note: "末尾は LAST_VALUE だが、既定の範囲は「今の行まで」なので ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING を付ける",
        keywords: ["先頭"],
      },
      {
        name: "NTILE",
        signature: "NTILE(分割数) OVER (ORDER BY 列)",
        summary: "並べた行を指定の数の組に分ける",
        example: "SELECT v, NTILE(2) OVER (ORDER BY v) FROM (VALUES (10),(20),(30),(40)) t(v)",
        result: "10 | 1\n20 | 1\n30 | 2\n40 | 2",
        keywords: ["分割", "四分位"],
      },
      {
        name: "DISTINCT ON",
        signature: "SELECT DISTINCT ON (列) ... ORDER BY 列, 並べ替えたい列",
        summary: "指定した列ごとに先頭の1行だけを取る",
        example: "SELECT DISTINCT ON (k) k, v FROM (VALUES ('a',1),('a',2),('b',3)) t(k,v) ORDER BY k, v DESC",
        result: "a | 2\nb | 3",
        note: "PostgreSQL独自。ORDER BY の先頭は DISTINCT ON に書いた列と同じにする必要がある。「グループごとの最新1件」を短く書ける",
        keywords: ["グループごと", "最新1件", "重複除外"],
      },
    ],
  },
];
