/** PostgreSQL: 日付・時刻の関数 */
import type { SqlFuncGroup } from "../types";

export const PG_DATETIME: SqlFuncGroup[] = [
  {
    category: "日付・時刻",
    items: [
      {
        name: "NOW",
        signature: "NOW()",
        summary: "今の日時をタイムゾーン付きで返す",
        example: "SELECT NOW()",
        result: "2026-09-04 12:34:56+09 (実行した時刻による)",
        note: "トランザクションの開始時刻を返す。文ごとに取り直したいときは STATEMENT_TIMESTAMP()、時計そのものは CLOCK_TIMESTAMP()。CURRENT_TIMESTAMP も同じ",
        keywords: ["現在", "今", "CURRENT_TIMESTAMP"],
      },
      {
        name: "CURRENT_DATE",
        signature: "CURRENT_DATE",
        summary: "今日の日付を返す",
        example: "SELECT CURRENT_DATE",
        result: "2026-09-04 (実行した日による)",
        note: "括弧は付けない。「今日のぶん」を絞るなら `at >= CURRENT_DATE AND at < CURRENT_DATE + 1` と書くと索引が効く",
        keywords: ["今日"],
      },
      {
        name: "TO_CHAR (日時)",
        signature: "TO_CHAR(日時, 書式)",
        summary: "日時を指定の書式の文字列にする",
        example: "SELECT TO_CHAR(TIMESTAMP '2026-09-04 15:06:07', 'YYYY/MM/DD HH24:MI:SS')",
        result: "2026/09/04 15:06:07",
        note: "MySQLの DATE_FORMAT にあたる。24時間表記は HH ではなく HH24、分は MI (ここを間違えやすい)。曜日は Day / Dy",
        keywords: ["書式", "フォーマット", "整形", "DATE_FORMAT"],
      },
      {
        name: "TO_DATE",
        signature: "TO_DATE(文字列, 書式)",
        summary: "文字列を書式に沿って日付に直す",
        example: "SELECT TO_DATE('2026年09月04日', 'YYYY年MM月DD日')",
        result: "2026-09-04",
        note: "時刻も要るなら TO_TIMESTAMP",
        keywords: ["変換", "パース"],
      },
      {
        name: "TO_TIMESTAMP",
        signature: "TO_TIMESTAMP(文字列, 書式) / TO_TIMESTAMP(秒数)",
        summary: "文字列または秒数を日時に直す",
        example: "SELECT TO_TIMESTAMP('2026-09-04 15:06', 'YYYY-MM-DD HH24:MI')",
        result: "2026-09-04 15:06:00+00 (接続のタイムゾーンによる)",
        note: "数値を渡すと 1970-01-01 からの秒数として扱う (MySQLの FROM_UNIXTIME にあたる)",
        keywords: ["変換", "エポック", "unixtime"],
      },
      {
        name: "DATE_TRUNC",
        signature: "DATE_TRUNC('単位', 日時)",
        summary: "指定の単位で切り捨てる",
        example: "SELECT DATE_TRUNC('month', TIMESTAMP '2026-09-04 15:06:07')",
        result: "2026-09-01 00:00:00",
        note: "単位は 'year' 'quarter' 'month' 'week' 'day' 'hour' 'minute' 'second'。月初・週初を出す定番",
        keywords: ["切り捨て", "月初", "週初", "丸め"],
      },
      {
        name: "EXTRACT",
        signature: "EXTRACT(単位 FROM 日時)",
        summary: "年・月・日などを取り出す",
        example: "SELECT EXTRACT(MONTH FROM DATE '2026-09-04')",
        result: "9",
        note: "単位は YEAR MONTH DAY HOUR MINUTE SECOND DOW(0=日曜) ISODOW(1=月曜) DOY QUARTER EPOCH。DATE_PART('month', 日時) と書いても同じ",
        keywords: ["取り出し", "年", "月", "日", "DATE_PART"],
      },
      {
        name: "AGE",
        signature: "AGE(日時1 [, 日時2])",
        summary: "2つの日時の差を「n年nか月n日」で返す",
        example: "SELECT AGE(DATE '2026-09-04', DATE '1990-09-05')",
        result: "35 years 11 mons 29 days",
        note: "引数が1つだと今日との差。年齢は EXTRACT(YEAR FROM AGE(誕生日)) で取れる",
        keywords: ["差", "年齢", "経過"],
      },
      {
        name: "INTERVAL",
        signature: "日時 + INTERVAL '数 単位'",
        summary: "日時に足したり引いたりする",
        example: "SELECT DATE '2026-01-31' + INTERVAL '1 month'",
        result: "2026-02-28 00:00:00",
        note: "単位は second minute hour day week month year。'1 day 2 hours' のようにまとめて書ける。MySQLの DATE_ADD にあたる",
        keywords: ["加算", "減算", "翌月", "前日", "DATE_ADD"],
      },
      {
        name: "日付の引き算",
        signature: "日付1 - 日付2",
        summary: "日数の差を返す",
        example: "SELECT DATE '2026-09-04' - DATE '2026-08-28'",
        result: "7",
        note: "date どうしなら整数の日数。timestamp どうしだと interval になるので、日数が欲しいときは EXTRACT(DAY FROM ...) か日付に落としてから引く",
        keywords: ["差", "日数", "DATEDIFF"],
      },
      {
        name: "MAKE_DATE",
        signature: "MAKE_DATE(年, 月, 日)",
        summary: "数値から日付を作る",
        example: "SELECT MAKE_DATE(2026, 9, 4)",
        result: "2026-09-04",
        note: "時刻も要るなら MAKE_TIMESTAMP(年,月,日,時,分,秒)",
        keywords: ["日付を作る"],
      },
      {
        name: "AT TIME ZONE",
        signature: "日時 AT TIME ZONE 'タイムゾーン'",
        summary: "タイムゾーンを付け替える",
        example: "SELECT TIMESTAMP WITH TIME ZONE '2026-09-04 00:00:00+00' AT TIME ZONE 'Asia/Tokyo'",
        result: "2026-09-04 09:00:00",
        note: "timestamptz に使うと「その地域での見え方 (timestamp)」に、timestamp に使うと「その地域の時刻とみなした瞬間 (timestamptz)」になる。向きが逆なので取り違えやすい",
        keywords: ["タイムゾーン", "時差", "JST", "UTC"],
      },
      {
        name: "GENERATE_SERIES (日付)",
        signature: "GENERATE_SERIES(開始, 終了, 間隔)",
        summary: "連続した日付を行として作る",
        example: "SELECT COUNT(*) FROM GENERATE_SERIES(DATE '2026-09-01', DATE '2026-09-30', INTERVAL '1 day')",
        result: "30",
        note: "データの無い日も0件として出したいときに、これと LEFT JOIN する",
        keywords: ["連番", "日付の一覧", "カレンダー", "欠損日"],
      },
    ],
  },
];
