/** PostgreSQL: 条件・NULL・JSON・配列・その他 */
import type { SqlFuncGroup } from "../types";

export const PG_MISC: SqlFuncGroup[] = [
  {
    category: "条件・NULL",
    items: [
      {
        name: "CASE",
        signature: "CASE WHEN 条件 THEN 値 [WHEN ...] [ELSE 値] END",
        summary: "条件で値を振り分ける",
        example: "SELECT CASE WHEN 5 > 3 THEN '大' ELSE '小' END",
        result: "大",
        note: "PostgreSQLには IF() が無いので、条件分岐はこれを使う。ELSE を書かないと NULL になる",
        keywords: ["条件", "分岐", "IF"],
      },
      {
        name: "COALESCE",
        signature: "COALESCE(値1, 値2, ...)",
        summary: "最初にNULLでなかった値を返す",
        example: "SELECT COALESCE(NULL, NULL, 'A', 'B')",
        result: "A",
        note: "MySQLの IFNULL にあたる (こちらは何個でも並べられる)",
        keywords: ["NULL", "既定値", "IFNULL"],
      },
      {
        name: "NULLIF",
        signature: "NULLIF(値1, 値2)",
        summary: "2つが同じならNULL、違えば値1を返す",
        example: "SELECT NULLIF('', '')",
        result: "NULL",
        note: "0除算を避けるのに使う (`v / NULLIF(w, 0)`)。PostgreSQLは0で割るとエラーになるので、この形が要る場面が多い",
        keywords: ["NULL", "0除算"],
      },
      {
        name: "IS NULL",
        signature: "値 IS NULL / 値 IS NOT NULL",
        summary: "NULLかどうかを調べる",
        example: "SELECT NULL IS NULL, (NULL = NULL) IS NULL",
        result: "t | t",
        note: "`= NULL` では判定できない (結果がNULLになる)",
        keywords: ["NULL", "判定"],
      },
      {
        name: "IS DISTINCT FROM",
        signature: "値1 IS DISTINCT FROM 値2",
        summary: "NULLも値の1つとみなして「違うか」を調べる",
        example: "SELECT NULL IS DISTINCT FROM NULL, 1 IS DISTINCT FROM NULL",
        result: "f | t",
        note: "MySQLの `<=>` の逆にあたる。NULLを含む列の突き合わせに使う",
        keywords: ["NULL", "比較", "差分"],
      },
      {
        name: "GREATEST/LEAST (NULL)",
        signature: "GREATEST(値1, 値2, ...)",
        summary: "NULLを飛ばして一番大きい値を返す",
        example: "SELECT GREATEST(1, NULL, 3)",
        result: "3",
        note: "MySQLでは1つでもNULLがあると結果がNULLになる。移すときに結果が変わる所",
        keywords: ["最大", "NULL"],
      },
    ],
  },
  {
    category: "JSON",
    items: [
      {
        name: "->",
        signature: "JSON -> キー",
        summary: "JSONから値をJSONのまま取り出す",
        example: "SELECT '{\"a\": {\"b\": 1}}'::jsonb -> 'a' -> 'b'",
        result: "1",
        note: "配列なら `-> 0` のように番号で取る。文字として欲しいときは `->>`",
        keywords: ["JSON", "取り出し"],
      },
      {
        name: "->>",
        signature: "JSON ->> キー",
        summary: "JSONから値を文字列として取り出す",
        example: "SELECT '{\"a\": \"x\"}'::jsonb ->> 'a'",
        result: "x",
        note: "`->` は引用符付きのJSON、`->>` は中身の文字列。ここを取り違えやすい",
        keywords: ["JSON", "取り出し", "文字列"],
      },
      {
        name: "#>>",
        signature: "JSON #>> '{階層,階層}'",
        summary: "深い所の値を文字列として取り出す",
        example: "SELECT '{\"a\": {\"b\": \"x\"}}'::jsonb #>> '{a,b}'",
        result: "x",
        keywords: ["JSON", "階層", "パス"],
      },
      {
        name: "@>",
        signature: "JSON @> 部分のJSON",
        summary: "そのJSONを含むかを調べる",
        example: "SELECT '{\"a\": 1, \"b\": 2}'::jsonb @> '{\"a\": 1}'",
        result: "t",
        note: "jsonb にGIN索引を張れば、この条件で索引が効く",
        keywords: ["JSON", "含む", "検索"],
      },
      {
        name: "JSONB_BUILD_OBJECT",
        signature: "JSONB_BUILD_OBJECT(キー1, 値1, ...)",
        summary: "JSONのオブジェクトを作る",
        example: "SELECT JSONB_BUILD_OBJECT('id', 1, 'name', 'A')",
        result: '{"id": 1, "name": "A"}',
        keywords: ["JSON", "作る"],
      },
      {
        name: "JSONB_ARRAY_ELEMENTS",
        signature: "JSONB_ARRAY_ELEMENTS(JSONの配列)",
        summary: "JSONの配列を行に開く",
        example: "SELECT STRING_AGG(e::text, ',') FROM JSONB_ARRAY_ELEMENTS('[1,2,3]'::jsonb) e",
        result: "1,2,3",
        note: "中身が文字列なら JSONB_ARRAY_ELEMENTS_TEXT のほうが扱いやすい",
        keywords: ["JSON", "展開", "行に開く"],
      },
      {
        name: "JSONB_OBJECT_KEYS",
        signature: "JSONB_OBJECT_KEYS(JSON)",
        summary: "キーを行として返す",
        example: "SELECT STRING_AGG(k, ',') FROM JSONB_OBJECT_KEYS('{\"a\":1,\"b\":2}'::jsonb) k",
        result: "a,b",
        keywords: ["JSON", "キー"],
      },
      {
        name: "ROW_TO_JSON",
        signature: "ROW_TO_JSON(行)",
        summary: "行をまるごとJSONにする",
        example: "SELECT ROW_TO_JSON(t) FROM (SELECT 1 AS id, 'A' AS name) t",
        result: '{"id":1,"name":"A"}',
        keywords: ["JSON", "行"],
      },
    ],
  },
  {
    category: "配列",
    items: [
      {
        name: "= ANY",
        signature: "値 = ANY(配列)",
        summary: "配列の中にあるかを調べる",
        example: "SELECT 2 = ANY(ARRAY[1,2,3])",
        result: "t",
        note: "IN と同じ意味。プレースホルダに配列を1つ渡せるので、件数の決まらない IN の代わりに使える",
        keywords: ["IN", "含む", "配列"],
      },
      {
        name: "UNNEST",
        signature: "UNNEST(配列)",
        summary: "配列を行に開く",
        example: "SELECT STRING_AGG(x, '-') FROM UNNEST(ARRAY['a','b']) x",
        result: "a-b",
        note: "STRING_TO_ARRAY と組み合わせると、カンマ区切りの文字列を行にできる",
        keywords: ["配列", "展開", "行に開く"],
      },
      {
        name: "ARRAY_LENGTH",
        signature: "ARRAY_LENGTH(配列, 次元)",
        summary: "配列の要素数を返す",
        example: "SELECT ARRAY_LENGTH(ARRAY[1,2,3], 1)",
        result: "3",
        note: "次元は普通 1。空の配列では0ではなくNULLが返る",
        keywords: ["配列", "件数"],
      },
      {
        name: "ARRAY_TO_STRING",
        signature: "ARRAY_TO_STRING(配列, 区切り文字)",
        summary: "配列を1つの文字列にする",
        example: "SELECT ARRAY_TO_STRING(ARRAY['a','b','c'], ',')",
        result: "a,b,c",
        keywords: ["配列", "連結"],
      },
    ],
  },
  {
    category: "その他",
    items: [
      {
        name: "CURRENT_DATABASE",
        signature: "CURRENT_DATABASE()",
        summary: "今つないでいるデータベース名を返す",
        example: "SELECT CURRENT_DATABASE()",
        result: "つないでいるDB名 (接続による)",
        keywords: ["DB名"],
      },
      {
        name: "CURRENT_SCHEMA",
        signature: "CURRENT_SCHEMA()",
        summary: "今のスキーマ名を返す",
        example: "SELECT CURRENT_SCHEMA()",
        result: "public (search_pathによる)",
        keywords: ["スキーマ"],
      },
      {
        name: "CURRENT_USER",
        signature: "CURRENT_USER",
        summary: "今の接続ユーザーを返す",
        example: "SELECT CURRENT_USER",
        result: "接続ユーザー名 (接続による)",
        note: "括弧は付けない",
        keywords: ["ユーザー"],
      },
      {
        name: "VERSION",
        signature: "VERSION()",
        summary: "サーバーの版を返す",
        example: "SELECT VERSION()",
        result: "PostgreSQL 16.x ... (接続による)",
        keywords: ["バージョン"],
      },
      {
        name: "PG_TYPEOF",
        signature: "PG_TYPEOF(値)",
        summary: "値の型を返す",
        example: "SELECT PG_TYPEOF(1), PG_TYPEOF(1.0)",
        result: "integer | numeric",
        note: "型が合わずにエラーになったとき、何型として扱われているかを確かめられる",
        keywords: ["型", "調べる"],
      },
      {
        name: "PG_SIZE_PRETTY",
        signature: "PG_SIZE_PRETTY(バイト数)",
        summary: "バイト数を読みやすい単位にする",
        example: "SELECT PG_SIZE_PRETTY(1536::bigint)",
        result: "1536 bytes",
        note: "PG_TOTAL_RELATION_SIZE('テーブル名') と組み合わせて、表の大きさを見るのに使う",
        keywords: ["サイズ", "容量"],
      },
      {
        name: "GEN_RANDOM_UUID",
        signature: "GEN_RANDOM_UUID()",
        summary: "重複しないIDを作る",
        example: "SELECT GEN_RANDOM_UUID()",
        result: "実行のたびに変わる",
        since: "PostgreSQL 13",
        note: "古い版では pgcrypto 拡張が要る",
        keywords: ["UUID", "採番"],
      },
    ],
  },
];
