/** PostgreSQL: 数値と型変換の関数 */
import type { SqlFuncGroup } from "../types";

export const PG_NUMBER: SqlFuncGroup[] = [
  {
    category: "数値",
    items: [
      {
        name: "ROUND",
        signature: "ROUND(数値 [, 小数桁数])",
        summary: "四捨五入する",
        example: "SELECT ROUND(1234.5678, 2)",
        result: "1234.57",
        note: "桁数を指定できるのは numeric のときだけ。float8 の列は `ROUND(v::numeric, 2)` と直してから渡す (ここでよく型のエラーになる)",
        keywords: ["四捨五入", "丸め"],
      },
      {
        name: "TRUNC",
        signature: "TRUNC(数値 [, 小数桁数])",
        summary: "切り捨てる (0に近づける)",
        example: "SELECT TRUNC(-1.7), TRUNC(1234.5678, 2)",
        result: "-1 | 1234.56",
        note: "FLOOR と違い、負の数では0に近づく",
        keywords: ["切り捨て"],
      },
      {
        name: "CEIL",
        signature: "CEIL(数値)",
        summary: "切り上げる",
        example: "SELECT CEIL(1.2)",
        result: "2",
        note: "CEILING も同じ",
        keywords: ["切り上げ"],
      },
      {
        name: "FLOOR",
        signature: "FLOOR(数値)",
        summary: "切り下げる",
        example: "SELECT FLOOR(-1.2)",
        result: "-2",
        keywords: ["切り捨て"],
      },
      {
        name: "ABS",
        signature: "ABS(数値)",
        summary: "絶対値を返す",
        example: "SELECT ABS(-12.5)",
        result: "12.5",
        keywords: ["絶対値"],
      },
      {
        name: "MOD",
        signature: "MOD(数値, 割る数)",
        summary: "割った余りを返す",
        example: "SELECT MOD(10, 3)",
        result: "1",
        note: "`10 % 3` と書いても同じ。0で割るとエラーになる (MySQLはNULL)",
        keywords: ["余り", "剰余"],
      },
      {
        name: "整数どうしの割り算",
        signature: "整数 / 整数",
        summary: "整数どうしだと小数が出ない",
        example: "SELECT 7 / 2, 7::numeric / 2",
        result: "3 | 3.5000000000000000",
        note: "割合を出すときに0になりがちな所。どちらかを numeric や 1.0 倍にしてから割る",
        keywords: ["割り算", "割合", "小数"],
      },
      {
        name: "POWER",
        signature: "POWER(数値, 指数)",
        summary: "べき乗を返す",
        example: "SELECT POWER(2, 10)",
        result: "1024",
        keywords: ["べき乗", "累乗"],
      },
      {
        name: "SQRT",
        signature: "SQRT(数値)",
        summary: "平方根を返す",
        example: "SELECT SQRT(16)",
        result: "4",
        keywords: ["平方根"],
      },
      {
        name: "SIGN",
        signature: "SIGN(数値)",
        summary: "符号を返す (正=1 / 0=0 / 負=-1)",
        example: "SELECT SIGN(-3)",
        result: "-1",
        keywords: ["符号"],
      },
      {
        name: "GREATEST",
        signature: "GREATEST(値1, 値2, ...)",
        summary: "並べた値のうち一番大きいものを返す",
        example: "SELECT GREATEST(3, 9, 5)",
        result: "9",
        note: "MySQLと違い、NULLは飛ばして比べる",
        keywords: ["最大"],
      },
      {
        name: "LEAST",
        signature: "LEAST(値1, 値2, ...)",
        summary: "並べた値のうち一番小さいものを返す",
        example: "SELECT LEAST(3, 9, 5)",
        result: "3",
        keywords: ["最小"],
      },
      {
        name: "RANDOM",
        signature: "RANDOM()",
        summary: "0以上1未満の乱数を返す",
        example: "SELECT FLOOR(RANDOM() * 100)",
        result: "0〜99 のどれか (実行のたびに変わる)",
        keywords: ["乱数", "ランダム"],
      },
      {
        name: "GENERATE_SERIES",
        signature: "GENERATE_SERIES(開始, 終了 [, 間隔])",
        summary: "連番を行として作る",
        example: "SELECT STRING_AGG(g::text, ',') FROM GENERATE_SERIES(1, 5) g",
        result: "1,2,3,4,5",
        note: "テスト用のデータ作りや、抜けのある番号を埋めるのに使う",
        keywords: ["連番", "行を作る"],
      },
    ],
  },
  {
    category: "型変換",
    items: [
      {
        name: "::",
        signature: "値::型",
        summary: "型を変える (PostgreSQL独自の短い書き方)",
        example: "SELECT '0123'::int",
        result: "123",
        note: "CAST(値 AS 型) と同じ。数値にすると前ゼロは消える",
        keywords: ["変換", "キャスト", "型"],
      },
      {
        name: "CAST",
        signature: "CAST(値 AS 型)",
        summary: "型を変える",
        example: "SELECT CAST('12.7' AS numeric)",
        result: "12.7",
        note: "型は int / bigint / numeric(桁,小数) / text / date / timestamp / boolean / json / jsonb など",
        keywords: ["変換", "キャスト"],
      },
      {
        name: "TO_NUMBER",
        signature: "TO_NUMBER(文字列, 書式)",
        summary: "書式を指定して文字列を数値にする",
        example: "SELECT TO_NUMBER('1,234.56', '999,999.99')",
        result: "1234.56",
        note: "カンマ入りの文字列を数値に戻すときに使う",
        keywords: ["変換", "カンマ"],
      },
    ],
  },
];
