/** PostgreSQL: 文字列と正規表現の関数 */
import type { SqlFuncGroup } from "../types";

export const PG_TEXT: SqlFuncGroup[] = [
  {
    category: "文字列",
    items: [
      {
        name: "||",
        signature: "文字列1 || 文字列2",
        summary: "文字列をつなげる",
        example: "SELECT 'A' || '-' || 'B'",
        result: "A-B",
        note: "1つでもNULLがあると全体がNULLになる。NULLを空文字として扱いたいときは CONCAT か COALESCE を使う",
        keywords: ["連結", "結合", "つなげる", "CONCAT"],
      },
      {
        name: "CONCAT",
        signature: "CONCAT(値1, 値2, ...)",
        summary: "文字列をつなげる (NULLは空文字として扱う)",
        example: "SELECT CONCAT('A', NULL, 'B')",
        result: "AB",
        note: "`||` と違い、NULLがあっても消えない。区切り文字を挟むなら CONCAT_WS",
        keywords: ["連結", "NULL"],
      },
      {
        name: "CONCAT_WS",
        signature: "CONCAT_WS(区切り文字, 値1, 値2, ...)",
        summary: "区切り文字を挟んでつなげる (NULLは飛ばす)",
        example: "SELECT CONCAT_WS('/', '2026', NULL, '04')",
        result: "2026/04",
        keywords: ["連結", "区切り"],
      },
      {
        name: "SUBSTRING",
        signature: "SUBSTRING(文字列 FROM 開始位置 FOR 長さ)",
        summary: "文字列の一部を取り出す",
        example: "SELECT SUBSTRING('ABCDE' FROM 2 FOR 3)",
        result: "BCD",
        note: "1始まり。`SUBSTRING(文字列, 開始, 長さ)` とカンマで書いても同じ。SUBSTR も使える",
        keywords: ["部分", "切り出し", "SUBSTR"],
      },
      {
        name: "LEFT",
        signature: "LEFT(文字列, 文字数)",
        summary: "左から指定の文字数を取り出す",
        example: "SELECT LEFT('2026-09-04', 7)",
        result: "2026-09",
        note: "負の数を渡すと「末尾のn文字を除いた残り」になる",
        keywords: ["先頭"],
      },
      {
        name: "RIGHT",
        signature: "RIGHT(文字列, 文字数)",
        summary: "右から指定の文字数を取り出す",
        example: "SELECT RIGHT('ORD-000123', 6)",
        result: "000123",
        keywords: ["末尾"],
      },
      {
        name: "LENGTH",
        signature: "LENGTH(文字列)",
        summary: "文字数を返す",
        example: "SELECT LENGTH('あいう')",
        result: "3",
        note: "MySQLと違い、こちらは文字数。バイト数が欲しいときは OCTET_LENGTH",
        keywords: ["長さ", "文字数", "CHAR_LENGTH"],
      },
      {
        name: "OCTET_LENGTH",
        signature: "OCTET_LENGTH(文字列)",
        summary: "バイト数を返す",
        example: "SELECT OCTET_LENGTH('あいう')",
        result: "9",
        keywords: ["バイト", "長さ"],
      },
      {
        name: "UPPER",
        signature: "UPPER(文字列)",
        summary: "大文字にする",
        example: "SELECT UPPER('abc')",
        result: "ABC",
        keywords: ["大文字"],
      },
      {
        name: "LOWER",
        signature: "LOWER(文字列)",
        summary: "小文字にする",
        example: "SELECT LOWER('ABC')",
        result: "abc",
        keywords: ["小文字"],
      },
      {
        name: "INITCAP",
        signature: "INITCAP(文字列)",
        summary: "単語の頭だけを大文字にする",
        example: "SELECT INITCAP('hello world')",
        result: "Hello World",
        keywords: ["先頭大文字"],
      },
      {
        name: "TRIM",
        signature: "TRIM([{BOTH|LEADING|TRAILING}] [削る文字] FROM 文字列)",
        summary: "前後の空白 (または指定の文字) を削る",
        example: "SELECT TRIM(LEADING '0' FROM '000123')",
        result: "123",
        note: "片側だけなら LTRIM / RTRIM。BTRIM(文字列, 削る文字) でも同じことができる",
        keywords: ["空白", "前ゼロ"],
      },
      {
        name: "LPAD",
        signature: "LPAD(文字列, 全体の長さ, 埋める文字)",
        summary: "左を埋めて指定の長さにする",
        example: "SELECT LPAD('123', 8, '0')",
        result: "00000123",
        keywords: ["前ゼロ", "ゼロ埋め", "桁揃え"],
      },
      {
        name: "RPAD",
        signature: "RPAD(文字列, 全体の長さ, 埋める文字)",
        summary: "右を埋めて指定の長さにする",
        example: "SELECT '[' || RPAD('ab', 5, '.') || ']'",
        result: "[ab...]",
        keywords: ["桁揃え", "固定長"],
      },
      {
        name: "REPLACE",
        signature: "REPLACE(文字列, 探す文字列, 置き換える文字列)",
        summary: "文字列を置き換える (すべて)",
        example: "SELECT REPLACE('2026/09/04', '/', '-')",
        result: "2026-09-04",
        keywords: ["置換"],
      },
      {
        name: "POSITION",
        signature: "POSITION(探す文字列 IN 文字列)",
        summary: "見つかった位置を返す (無ければ0)",
        example: "SELECT POSITION('cd' IN 'abcdef')",
        result: "3",
        note: "1始まり。STRPOS(文字列, 探す文字列) と書いても同じ (引数の順に注意)",
        keywords: ["検索", "位置", "STRPOS", "含む"],
      },
      {
        name: "SPLIT_PART",
        signature: "SPLIT_PART(文字列, 区切り文字, 何番目)",
        summary: "区切り文字で分けて、指定の番号のものを取り出す",
        example: "SELECT SPLIT_PART('a.b.c', '.', 2)",
        result: "b",
        note: "1始まり。範囲を超えると空文字。MySQLの SUBSTRING_INDEX にあたる",
        keywords: ["分割", "区切り", "split"],
      },
      {
        name: "STRING_TO_ARRAY",
        signature: "STRING_TO_ARRAY(文字列, 区切り文字)",
        summary: "区切り文字で分けて配列にする",
        example: "SELECT STRING_TO_ARRAY('a,b,c', ',')",
        result: "{a,b,c}",
        note: "UNNEST と組み合わせると、カンマ区切りを行に開ける",
        keywords: ["分割", "配列"],
      },
      {
        name: "REPEAT",
        signature: "REPEAT(文字列, 回数)",
        summary: "文字列を繰り返す",
        example: "SELECT REPEAT('ab', 3)",
        result: "ababab",
        keywords: ["繰り返し"],
      },
      {
        name: "REVERSE",
        signature: "REVERSE(文字列)",
        summary: "文字を逆順にする",
        example: "SELECT REVERSE('abc')",
        result: "cba",
        keywords: ["逆順"],
      },
      {
        name: "TO_CHAR (数値)",
        signature: "TO_CHAR(数値, 書式)",
        summary: "数値を書式に沿った文字列にする",
        example: "SELECT TO_CHAR(1234567.891, 'FM999,999,999.00')",
        result: "1,234,567.89",
        note: "FM を付けないと桁揃えの空白が入る。9=数字(空白埋め) 0=数字(ゼロ埋め)",
        keywords: ["書式", "カンマ", "桁区切り", "ゼロ埋め"],
      },
      {
        name: "MD5",
        signature: "MD5(文字列)",
        summary: "MD5のハッシュ値 (32文字) を返す",
        example: "SELECT MD5('abc')",
        result: "900150983cd24fb0d6963f7d28e17f72",
        keywords: ["ハッシュ"],
      },
      {
        name: "FORMAT",
        signature: "FORMAT(書式, 値1, 値2, ...)",
        summary: "書式に値を差し込む",
        example: "SELECT FORMAT('%s は %s 件', 'A', 3)",
        result: "A は 3 件",
        note: "%I は識別子、%L は文字列リテラルとして安全に引用符を付ける (動的SQLを組み立てるときに使う)",
        keywords: ["書式", "埋め込み"],
      },
    ],
  },
  {
    category: "正規表現",
    items: [
      {
        name: "~",
        signature: "文字列 ~ パターン / 文字列 ~* パターン",
        summary: "正規表現に当てはまるかを調べる",
        example: "SELECT 'AB-123' ~ '^[A-Z]{2}-[0-9]+$'",
        result: "t",
        note: "`~*` は大文字小文字を区別しない。当てはまらないことを調べるなら `!~`",
        keywords: ["正規表現", "一致", "REGEXP"],
      },
      {
        name: "REGEXP_REPLACE",
        signature: "REGEXP_REPLACE(文字列, パターン, 置換文字列 [, オプション])",
        summary: "正規表現に当てはまった部分を置き換える",
        example: "SELECT REGEXP_REPLACE('a1b2c3', '[0-9]', '', 'g')",
        result: "abc",
        note: "既定では最初の1件だけ。すべて置き換えるにはオプションに 'g' を渡す (ここを忘れやすい)",
        keywords: ["正規表現", "置換"],
      },
      {
        name: "REGEXP_MATCHES",
        signature: "REGEXP_MATCHES(文字列, パターン [, オプション])",
        summary: "括弧で囲んだ部分を配列で取り出す",
        example: "SELECT (REGEXP_MATCHES('ORD-123', '([A-Z]+)-([0-9]+)'))[2]",
        result: "123",
        note: "行を返す関数なので、SELECT の並びに書くと行が増えることがある。1件だけ欲しいときは括弧でくくって添字を取る",
        keywords: ["正規表現", "抽出", "グループ"],
      },
      {
        name: "SUBSTRING (正規表現)",
        signature: "SUBSTRING(文字列 FROM パターン)",
        summary: "正規表現に当てはまった部分を取り出す",
        example: "SELECT SUBSTRING('注文 ORD-123 済' FROM '[A-Z]+-[0-9]+')",
        result: "ORD-123",
        note: "括弧を1つ書くと、その中身だけが返る",
        keywords: ["正規表現", "抽出"],
      },
      {
        name: "REGEXP_SPLIT_TO_ARRAY",
        signature: "REGEXP_SPLIT_TO_ARRAY(文字列, パターン)",
        summary: "正規表現で分けて配列にする",
        example: "SELECT REGEXP_SPLIT_TO_ARRAY('a1b22c', '[0-9]+')",
        result: "{a,b,c}",
        keywords: ["正規表現", "分割"],
      },
    ],
  },
];
